name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: sudo npm install

      - name: Build the project
        run: |
          cd client
          VITE_APP_API=https://api.greenbackclaims.com/ npm run build
          ls
         

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.SSH }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          scp -o StrictHostKeyChecking=no -i private_key -r client/dist/* ubuntu@54.224.199.167:/var/www/Greenback-Claims-main/
          echo "Deployment completed successfully!"

